# Generated by Django 5.2.7 on 2025-10-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(default='Nome da Empresa', help_text='Nome que aparecerá no título da página e cabeçalhos.', max_length=100)),
                ('logo', models.ImageField(blank=True, help_text='Faça upload do logo aqui (preferência por PNG transparente)', null=True, upload_to='logos/')),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configuração do Site',
            },
        ),
    ]
