# Generated by Django 5.2.7 on 2025-11-02 01:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguracao',
            name='default_from_email',
            field=models.EmailField(default='naoresponda@exemplo.com', help_text='O e-mail remetente padrão (FROM) que aparecerá para os clientes.', max_length=254, validators=[django.core.validators.EmailValidator]),
        ),
        migrations.AddField(
            model_name='siteconfiguracao',
            name='email_host',
            field=models.CharField(blank=True, help_text='Host do servidor SMTP (Ex: smtp.sendgrid.net)', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfiguracao',
            name='email_host_password',
            field=models.CharField(blank=True, help_text='Senha/API Secret do servidor SMTP (NUNCA armazene em código!)', max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfiguracao',
            name='email_host_user',
            field=models.CharField(blank=True, help_text='Usuário/API Key do servidor SMTP (Ex: apikey)', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfiguracao',
            name='email_port',
            field=models.IntegerField(default=587, help_text='Porta do servidor SMTP (Ex: 587 para TLS/STARTTLS)'),
        ),
        migrations.AddField(
            model_name='siteconfiguracao',
            name='email_use_tls',
            field=models.BooleanField(default=True, help_text='Usar Transport Layer Security (TLS/STARTTLS)?'),
        ),
    ]
