# Generated by Django 5.2.7 on 2025-10-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('rg', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('cnh', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nº CNH')),
                ('validade_cnh', models.DateField(blank=True, null=True, verbose_name='Validade CNH')),
                ('nome_mae', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome da Mãe')),
                ('nome_pai', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Pai')),
                ('estado_civil', models.CharField(blank=True, max_length=20, null=True, verbose_name='Estado Civil')),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('celular', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular')),
                ('cep_residencial', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP Residencial')),
                ('endereco_residencial', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço Residencial')),
                ('numero_residencial', models.CharField(blank=True, max_length=10, null=True, verbose_name='Nº')),
                ('bairro_residencial', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('cidade_residencial', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('estado_residencial', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('empresa', models.CharField(blank=True, max_length=200, null=True, verbose_name='Empresa onde trabalha')),
                ('cargo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo/Função')),
                ('renda_mensal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Renda Mensal')),
                ('telefone_comercial', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Comercial')),
                ('cep_comercial', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP Comercial')),
                ('endereco_comercial', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço Comercial')),
                ('ref_pessoal_nome', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ref. Pessoal: Nome')),
                ('ref_pessoal_telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Ref. Pessoal: Telefone')),
                ('ref_bancaria_banco', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ref. Bancária: Banco')),
                ('ref_bancaria_agencia', models.CharField(blank=True, max_length=20, null=True, verbose_name='Ref. Bancária: Agência')),
                ('ref_bancaria_conta', models.CharField(blank=True, max_length=20, null=True, verbose_name='Ref. Bancária: Conta')),
                ('condutor_nome', models.CharField(blank=True, max_length=200, null=True, verbose_name='Condutor Adicional: Nome')),
                ('condutor_data_nasc', models.DateField(blank=True, null=True, verbose_name='Condutor Adicional: Data Nasc.')),
                ('condutor_rg', models.CharField(blank=True, max_length=20, null=True, verbose_name='Condutor Adicional: RG')),
                ('condutor_cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='Condutor Adicional: CPF')),
                ('condutor_cnh', models.CharField(blank=True, max_length=20, null=True, verbose_name='Condutor Adicional: CNH')),
                ('condutor_validade_cnh', models.DateField(blank=True, null=True, verbose_name='Condutor Adicional: Validade CNH')),
                ('condutor_nome_mae', models.CharField(blank=True, max_length=200, null=True, verbose_name='Condutor Adicional: Nome da Mãe')),
                ('condutor_email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Condutor Adicional: Email')),
                ('condutor_telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Condutor Adicional: Telefone')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('tipo_pessoa', models.CharField(choices=[('F', 'Pessoa Física'), ('J', 'Pessoa Jurídica')], default='F', max_length=1, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['nome_completo'],
            },
        ),
    ]
