# Generated by Django 5.2.7 on 2025-10-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='rg_orgao_expeditor',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Órgão Expedidor'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rg_uf',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF RG'),
        ),
    ]
