# Generated by Django 5.2.7 on 2025-10-25 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_rg_orgao_expeditor_cliente_rg_uf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='condutor_cnh',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='condutor_cpf',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='condutor_data_nasc',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='condutor_email',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='condutor_nome_mae',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='condutor_rg',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='condutor_validade_cnh',
        ),
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Acesso'),
        ),
    ]
