# Generated by Django 5.2.7 on 2025-10-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_remove_cliente_condutor_cnh_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nome_completo'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='condutor_cnh',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Condutor Adicional: CNH'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='condutor_cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Condutor Adicional: CPF'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='condutor_data_nasc',
            field=models.DateField(blank=True, null=True, verbose_name='Condutor Adicional: Data Nasc.'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='condutor_email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Condutor Adicional: Email'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='condutor_nome_mae',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Condutor Adicional: Nome da Mãe'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='condutor_rg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Condutor Adicional: RG'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='condutor_validade_cnh',
            field=models.DateField(blank=True, null=True, verbose_name='Condutor Adicional: Validade CNH'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(error_messages={'unique': 'Cliente com esse CPF ja cadastrado!'}, max_length=11, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone (Fixo)'),
        ),
    ]
