# Generated by Django 5.2.7 on 2025-11-02 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_cliente_options_cliente_condutor_cnh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='complemento_comercial',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento Comercial'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='complemento_residencial',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='condutor_cnh',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nº CNH'),
        ),
    ]
