# Generated by Django 5.2.7 on 2025-11-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_cliente_complemento_comercial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='bairro_comercial',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro Comercial'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cidade_comercial',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade Comercial'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado_comercial',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF Comercial'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero_comercial',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Nº Comercial'),
        ),
    ]
