# Generated by Django 5.2.7 on 2025-11-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_cliente_bairro_comercial_cliente_cidade_comercial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='condutor2_cnh',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Condutor 2: Nº CNH'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='condutor2_cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Condutor 2: CPF'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='condutor2_data_nasc',
            field=models.DateField(blank=True, null=True, verbose_name='Condutor 2: Data Nasc.'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='condutor2_email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Condutor 2: Email'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='condutor2_nome',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Condutor 2: Nome'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='condutor2_telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Condutor 2: Telefone'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='condutor2_validade_cnh',
            field=models.DateField(blank=True, null=True, verbose_name='Condutor 2: Validade CNH'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='condutor3_cnh',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Condutor 3: Nº CNH'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='condutor3_cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Condutor 3: CPF'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='condutor3_data_nasc',
            field=models.DateField(blank=True, null=True, verbose_name='Condutor 3: Data Nasc.'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='condutor3_email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Condutor 3: Email'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='condutor3_nome',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Condutor 3: Nome'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='condutor3_telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Condutor 3: Telefone'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='condutor3_validade_cnh',
            field=models.DateField(blank=True, null=True, verbose_name='Condutor 3: Validade CNH'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='condutor_cnh',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Condutor 1: Nº CNH'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='condutor_cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Condutor 1: CPF'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='condutor_data_nasc',
            field=models.DateField(blank=True, null=True, verbose_name='Condutor 1: Data Nasc.'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='condutor_email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Condutor 1: Email'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='condutor_nome',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Condutor 1: Nome'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='condutor_nome_mae',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Condutor 1: Nome da Mãe'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='condutor_rg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Condutor 1: RG'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='condutor_telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Condutor 1: Telefone'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='condutor_validade_cnh',
            field=models.DateField(blank=True, null=True, verbose_name='Condutor 1: Validade CNH'),
        ),
    ]
